public enum PoolTag
{
    EnemyMiniMapIcon,
    MiniMapIconIppali,
    MiniMapIconIbkkugi,
    MiniMapIconKoppulso,
    MiniMapIconGiljjugi,
    MiniMapIconDulduli,
    MiniMapIconItmomi,
    IbkkugiThrow,
    ItmomiThrow,
    Soul,
    Ghost,
    Mark,
    Tentacle,
    TentacleVertical,
    TentacleHorizontal,
    Ippali,
    IppaliEgg
}