public enum MonsterName
{
    DummySoldierHP1,
    DummySoldierHP2,
    DummySoldierHP3,
    DummySoldierHP4,
    DummySoldierHP5,
    DummySoldierHP6,
    DummyArcherHP1,
    DummyArcherHP2,
    DummyArcherHP3,
    DummyArcherHP4,
    Ippali,
    Ibkkugi,
    Koppulso,
    Jiljili,
    Giljjugi,
    Ismomi
}